# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "jquery-3.3.1" = {
      name = "jquery";
      packageName = "jquery";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jquery/-/jquery-3.3.1.tgz";
        sha512 = "Ubldcmxp5np52/ENotGxlLe6aGMvmF4R8S6tZjsP6Knsaxd/xp3Zrh50cG93lR6nPXyUFwzN3ZSOQI0wRJNdGg==";
      };
    };
    "tether-1.4.3" = {
      name = "tether";
      packageName = "tether";
      version = "1.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/tether/-/tether-1.4.3.tgz";
        sha512 = "YCfE/Ym9MpZpzUmzbek7MiLEyTofxx2YS0rJfSOUXX0aZtfQgxcgw7/Re2oGJUsREWZtEF0DzBKCjqH+DzgL6A==";
      };
    };
  };
  args = {
    name = "bootstrap";
    packageName = "bootstrap";
    version = "4.0.0-alpha.6";
    src = ./.;
    dependencies = [
      sources."jquery-3.3.1"
      sources."tether-1.4.3"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The most popular front-end framework for developing responsive, mobile first projects on the web.";
      homepage = https://getbootstrap.com/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
  };
in
{
  tarball = nodeEnv.buildNodeSourceDist args;
  package = nodeEnv.buildNodePackage args;
  shell = nodeEnv.buildNodeShell args;
}
